repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args: [ "--exclude=backend/alembic/.*", "--exclude=backend/auth/Celery/logger_info.py" ]

  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: [
          "--force-grid-wrap=0",  # Всегда переносить импорты на новую строку
          "--lines-after-imports=2",  # 2 пустые строки после импортов
          "--line-length=100",  # Совместимость с flake8
          "--multi-line=3",  # Вертикальное выравнивание скобок
          "--trailing-comma",  # Добавлять запятую после последнего элемента
        ]

  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        # игнорировать E501
        args: [
          "--ignore=E501",
          "--max-line-length=100",
          "--exclude=backend/alembic/.*",
          "--exclude=backend/core/config,py",
        ]
        additional_dependencies: [ black ]


  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args: [ "--in-place", "--remove-unused-variables" ]

  - repo: https://github.com/myint/docformatter
    rev: v1.7.7
    hooks:
      - id: docformatter
        args: [ "--in-place" ]
        additional_dependencies: [ black ]

  - repo: https://github.com/asottile/blacken-docs
    rev: 1.19.1
    hooks:
      - id: blacken-docs
        additional_dependencies: [ black ]
