services:
  pg:
    image: postgres
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pg_test:
    image: postgres
    environment:
      POSTGRES_DB: test_database
      POSTGRES_USER: test_admin
      POSTGRES_PASSWORD: test_password
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5434:5432"
    volumes:
      - pgdata_test:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./backend/redis-data:/data
      - ./backend/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  flower:
    image: mher/flower:0.9.7
    platform: linux/amd64
    command: [ 'flower', '--broker=redis://redis:6379', '--port=5555' ]
    ports:
      - "5555:5555"
    depends_on:
      - redis

  rabbitmq:
    image: rabbitmq:3-management  #
    ports:
      - "5672:5672"
      - "15672:15672"  # UI доступен по localhost:15672  порт для подключения веб интерфейса
    environment:
      RABBITMQ_DEFAULT_USER: guest  # значение по умолчанию
      RABBITMQ_DEFAULT_PASS: guest  # значение по умолчанию

volumes:
  pgdata:
  pgdata_test:


