services:
  pg:
    image: postgres
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /Users/nikita/PycharmProjects/General_project/backend/redis-data:/data
      - /Users/nikita/PycharmProjects/General_project/backend/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf


  rabbitmq:
    image: rabbitmq:3-management  #
    ports:
      - "5672:5672"
      - "15672:15672"  # UI доступен по localhost:15672  порт для подключения веб интерфейса
    environment:
      RABBITMQ_DEFAULT_USER: guest  # значение по умолчанию
      RABBITMQ_DEFAULT_PASS: guest  # значение по умолчанию

volumes:
  pgdata:


