"""deleted fields tags, title

Revision ID: 56590931d5a4
Revises: 9ca89511aeea
Create Date: 2025-04-23 10:47:37.144240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56590931d5a4'
down_revision: Union[str, None] = '9ca89511aeea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_tags')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_tags',
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='fk_post_tags_post_id_posts'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name='fk_post_tags_tag_id_tags'),
    sa.PrimaryKeyConstraint('post_id', 'tag_id', name='pk_post_tags')
    )
    # ### end Alembic commands ###
