"""added cascade deleted for post

Revision ID: 9abe092df65d
Revises: f59b51a97910
Create Date: 2025-05-20 16:31:35.584512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9abe092df65d'
down_revision: Union[str, None] = 'f59b51a97910'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_like_posts_post_id_posts', 'like_posts', type_='foreignkey')
    op.create_foreign_key(op.f('fk_like_posts_post_id_posts'), 'like_posts', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_like_posts_post_id_posts'), 'like_posts', type_='foreignkey')
    op.create_foreign_key('fk_like_posts_post_id_posts', 'like_posts', 'posts', ['post_id'], ['id'])
    # ### end Alembic commands ###
