"""deleted fields tags, title

Revision ID: 9ca89511aeea
Revises: 69757955b30c
Create Date: 2025-04-23 10:45:21.231261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ca89511aeea'
down_revision: Union[str, None] = '69757955b30c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
