"""Fixed field content

Revision ID: ee5d07e0784a
Revises: f81bcff93f30
Create Date: 2025-06-02 19:11:26.415134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee5d07e0784a'
down_revision: Union[str, None] = 'f81bcff93f30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_like_posts_user_id_users', 'like_posts', type_='foreignkey')
    op.create_foreign_key(op.f('fk_like_posts_user_id_users'), 'like_posts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('posts', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_constraint(op.f('fk_like_posts_user_id_users'), 'like_posts', type_='foreignkey')
    op.create_foreign_key('fk_like_posts_user_id_users', 'like_posts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
